server:
  port: 8768
spring:
  application:
    name: server-zuul

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
# serviceId必须与相应的服务名字对应！
zuul:
  prefix: /shawn  #设置统一域名前缀
  routes:
   zuul-a:
     path: /zuul-a/**
     serviceId: consumer-ribbon
   zuul-b:
     path: /zuul-b/**
     serviceId: consumer-feign
   zuul-c:
     path: /zuul-c/**
     serviceId: ribbon-hystrix
   zuul-d:
     path: /zuul-d/**
     serviceId: feign-hystrix
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000

hystrix:
  command:
    c4i-store:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
            ribbon:
              ReadTimeout: 600000
              ConnectTimeout: 600000

#如果未配置以上的超时时间 就会com.netflix.zuul.exception.ZuulException: Forwarding error报错